version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Constantine@2016
  redis:
    image: redis
    ports:
      - 6379:6379
  vehicle-service:
    restart: on-failure
    ports:
      - "8761:8761"
    depends_on:
        - mysql
        - redis
    build: ./vehicles-api
    image: vehicle-service
    container_name: vehicles-service
  map-service:
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    build: ./map-service
    image: map-service
    container_name: map-service
  price-service:
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    build: ./pricing-service
    image: price-service
    container_name: price-service




